# Form implementation generated from reading ui file 'features1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from new_canvas import Ui_graph

class Ui_features1(object):
    def openwin(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_graph()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, features1):
        features1.setObjectName("features1")
        features1.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=features1)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 420, 782, 135))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 140, 782, 135))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 0, 782, 136))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.openwin)
        self.verticalLayout_6.addWidget(self.pushButton_9)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 280, 782, 136))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_7.addWidget(self.pushButton_8)
        features1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=features1)
        self.statusbar.setObjectName("statusbar")
        features1.setStatusBar(self.statusbar)

        self.retranslateUi(features1)
        QtCore.QMetaObject.connectSlotsByName(features1)

    def retranslateUi(self, features1):
        _translate = QtCore.QCoreApplication.translate
        features1.setWindowTitle(_translate("features1", "features1"))
        self.pushButton_5.setText(_translate("features1", "RECENTLY DELETED"))
        self.pushButton_6.setText(_translate("features1", "OBSCENE IMAGES AND VIDEOS DETECTED"))
        self.pushButton_9.setText(_translate("features1", "VULNERABILITY AND RISK GRAPHS "))
        self.pushButton_7.setText(_translate("features1", "SUSPICIOUS ACTIVITY DETECTION USING AI/ML"))
        self.pushButton_8.setText(_translate("features1", "SUSPICIOUS LOG FILES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    features1 = QtWidgets.QMainWindow()
    ui = Ui_features1()
    ui.setupUi(features1)
    features1.show()
    sys.exit(app.exec())
