# Form implementation generated from reading ui file 'features2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from new_canvas import Ui_graph

class Ui_features2(object):
    def openwin(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_graph()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, features2):
        features2.setObjectName("features2")
        features2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=features2)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_5.clicked.connect(self.openwin)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame)
        features2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=features2)
        self.statusbar.setObjectName("statusbar")
        features2.setStatusBar(self.statusbar)

        self.retranslateUi(features2)
        QtCore.QMetaObject.connectSlotsByName(features2)

    def retranslateUi(self, features2):
        _translate = QtCore.QCoreApplication.translate
        features2.setWindowTitle(_translate("features2", "features2"))
        self.pushButton_5.setText(_translate("features2", "VULNERABILITY AND RISK GRAPHS "))
        self.pushButton.setText(_translate("features2", "SUSPICIOUS ACTIVITY DETECTION USING AI/ML"))
        self.pushButton_2.setText(_translate("features2", "OBSCENE IMAGES AND VIDEOS DETECTED"))
        self.pushButton_3.setText(_translate("features2", "SUSPICIOUS LOG FILES"))
        self.pushButton_4.setText(_translate("features2", "RECENTLY DELETED"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    features2 = QtWidgets.QMainWindow()
    ui = Ui_features2()
    ui.setupUi(features2)
    features2.show()
    sys.exit(app.exec())
