# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from window6 import Ui_window6
from window7 import Ui_window7
from features2 import Ui_features2

class Ui_window2(object):
    def openwin2(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_features2()
        self.ui.setupUi(self.window)
        self.window.show()
    def openwin(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_window6()
        self.ui.setupUi(self.window)
        self.window.show()
    def openwin1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_window7()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, window2):
        window2.setObjectName("window2")
        window2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=window2)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.pushButton_2.clicked.connect(self.openwin)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton.clicked.connect(self.openwin1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.pushButton_3.clicked.connect(self.openwin2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 781, 41))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_2)
        window2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=window2)
        self.statusbar.setObjectName("statusbar")
        window2.setStatusBar(self.statusbar)

        self.retranslateUi(window2)
        QtCore.QMetaObject.connectSlotsByName(window2)

    def retranslateUi(self, window2):
        _translate = QtCore.QCoreApplication.translate
        window2.setWindowTitle(_translate("window2", "window2"))
        self.pushButton_2.setText(_translate("window2", "PHYSICAL IMAGING"))
        self.pushButton.setText(_translate("window2", "LOGICAL IMAGING"))
        self.pushButton_3.setText(_translate("window2", "SPECIAL FEATURES"))
        self.label.setText(_translate("window2", "EVENT LOGS "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window2 = QtWidgets.QMainWindow()
    ui = Ui_window2()
    ui.setupUi(window2)
    window2.show()
    sys.exit(app.exec())
