# Form implementation generated from reading ui file 'window4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from window3 import Ui_window3
from window5 import Ui_window5
from features1 import Ui_features1

class Ui_window4(object):
    def openwin2(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_features1()
        self.ui.setupUi(self.window)
        self.window.show()
    def openwin(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_window5()
        self.ui.setupUi(self.window)
        self.window.show()
    def openwin1(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_window3()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, window4):
        window4.setObjectName("window4")
        window4.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=window4)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.pushButton_5.clicked.connect(self.openwin)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton.clicked.connect(self.openwin2)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_6.clicked.connect(self.openwin1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 781, 41))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.frame_2)
        window4.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=window4)
        self.statusbar.setObjectName("statusbar")
        window4.setStatusBar(self.statusbar)

        self.retranslateUi(window4)
        QtCore.QMetaObject.connectSlotsByName(window4)

    def retranslateUi(self, window4):
        _translate = QtCore.QCoreApplication.translate
        window4.setWindowTitle(_translate("window4", "window4"))
        self.pushButton_5.setText(_translate("window4", "LOGICAL IMAGING"))
        self.pushButton.setText(_translate("window4", "SPECIAL FEATURES"))
        self.pushButton_6.setText(_translate("window4", "PHYSICAL IMAGING"))
        self.label_3.setText(_translate("window4", "EVENT LOGS "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window4 = QtWidgets.QMainWindow()
    ui = Ui_window4()
    ui.setupUi(window4)
    window4.show()
    sys.exit(app.exec())
